import os

import numpy as np
import pandas as pd

from scipy.stats import chi2_contingency, fisher_exact
from statsmodels.stats.contingency_tables import Table2x2
from statsmodels.stats.multitest import multipletests


# =========================================================
# Load sample groups
# =========================================================


def load_sample_groups(
    phenotype_file: str
) -> pd.DataFrame:
    """
    Load sample phenotype information.

    Parameters
    ----------
    phenotype_file : str
        Path to the phenotype/sample-group Excel file.

    Returns
    -------
    pandas.DataFrame
        Sample phenotype information.
    """

    return pd.read_excel(
        phenotype_file
    )


# =========================================================
# Create sample sets
# =========================================================


def create_sample_sets(
    phenotype_df: pd.DataFrame
):
    """
    Create case and control sample sets.

    Parameters
    ----------
    phenotype_df : pandas.DataFrame
        Phenotype table containing Sample and Group columns.

    Returns
    -------
    tuple of set
        Case sample IDs and control sample IDs.
    """

    required_columns = {
        "Sample",
        "Group"
    }

    missing_columns = (
        required_columns
        - set(phenotype_df.columns)
    )

    if missing_columns:
        raise ValueError(
            "Phenotype data are missing required columns: "
            f"{sorted(missing_columns)}"
        )

    case_samples = set(
        phenotype_df.loc[
            phenotype_df["Group"] == "Case",
            "Sample"
        ].astype(str)
    )

    control_samples = set(
        phenotype_df.loc[
            phenotype_df["Group"] == "Control",
            "Sample"
        ].astype(str)
    )

    return case_samples, control_samples


# =========================================================
# Prepare genotype data
# =========================================================


def prepare_genotype_data(
    genotype_df: pd.DataFrame,
    min_phred: int = 20
) -> pd.DataFrame:
    """
    Prepare genotype calls for association analysis.

    Only high-confidence genotype calls are retained.

    Samples with genotype calls below the minimum Phred
    threshold are not treated as non-carriers. They remain
    unavailable for variant-specific association analysis.

    Parameters
    ----------
    genotype_df : pandas.DataFrame
        Genotype calls generated by the variant-calling pipeline.

    min_phred : int, default=20
        Minimum Phred quality required for a genotype call.

    Returns
    -------
    pandas.DataFrame
        High-confidence genotype calls.
    """

    required_columns = {
        "Sample",
        "cDNA_Position",
        "Genotype",
        "Quality"
    }

    missing_columns = (
        required_columns
        - set(genotype_df.columns)
    )

    if missing_columns:
        raise ValueError(
            "Genotype data are missing required columns: "
            f"{sorted(missing_columns)}"
        )

    df = genotype_df.copy()

    df["Sample"] = df["Sample"].astype(str)

    df["Quality"] = pd.to_numeric(
        df["Quality"],
        errors="coerce"
    )

    df["Genotype"] = pd.to_numeric(
        df["Genotype"],
        errors="coerce"
    )

    # Keep only genotype calls meeting the
    # minimum sequencing-quality threshold.
    df = df[
        df["Quality"] >= min_phred
    ].copy()

    # Keep only valid genotype classifications:
    #
    # 0 = homozygous reference
    # 1 = heterozygous
    # 2 = homozygous variant
    #
    # Missing, ambiguous, and low-confidence genotype
    # calls are excluded from callable genotype data.
    df = df[
        df["Genotype"].isin(
            [0, 1, 2]
        )
    ].copy()

    return df


# =========================================================
# Get callable genotypes for a variant
# =========================================================


def get_variant_genotypes(
    variant,
    genotype_df: pd.DataFrame
) -> pd.DataFrame:
    """
    Retrieve valid genotype calls for one variant.

    The final variant table stores the transcript coordinate
    as ``Transcript_Position``. Genotype calls use
    ``cDNA_Position`` for the corresponding transcript
    coordinate.

    Parameters
    ----------
    variant : pandas.Series
        Variant record from the final variant table.

    genotype_df : pandas.DataFrame
        High-confidence genotype calls.

    Returns
    -------
    pandas.DataFrame
        One genotype record per callable sample at the
        variant position.
    """

    position = variant[
        "Transcript_Position"
    ]

    subset = genotype_df[
        genotype_df["cDNA_Position"] == position
    ].copy()

    if subset.empty:
        return subset

    # -----------------------------------------------------
    # Match REF/ALT when available.
    #
    # This prevents genotype calls at the same transcript
    # position from being incorrectly assigned to a
    # different nucleotide substitution.
    # -----------------------------------------------------

    if (
        "REF" in variant.index
        and "ALT" in variant.index
        and "REF" in subset.columns
        and "ALT" in subset.columns
    ):

        ref = variant["REF"]
        alt = variant["ALT"]

        if pd.notna(ref) and pd.notna(alt):

            subset = subset[
                (
                    subset["REF"].astype(str)
                    == str(ref)
                )
                & (
                    subset["ALT"].astype(str)
                    == str(alt)
                )
            ].copy()

    if subset.empty:
        return subset

    # -----------------------------------------------------
    # Ensure one genotype call per sample.
    #
    # If multiple records exist for the same sample and
    # variant, retain the highest-quality call.
    # -----------------------------------------------------

    subset = (
        subset
        .sort_values(
            by=["Sample", "Quality"],
            ascending=[True, False]
        )
        .drop_duplicates(
            subset=["Sample"],
            keep="first"
        )
    )

    return subset


# =========================================================
# Analyse individual variant
# =========================================================


def analyse_variant(
    row,
    genotype_df: pd.DataFrame,
    case_samples,
    control_samples
):
    """
    Analyse a single variant using a case-control
    carrier association framework.

    Only samples with a valid genotype call at the
    specific variant are included in the analysis.

    Samples without a callable genotype at the variant
    are treated as missing, not as non-carriers.

    Calculates
    ---------
    - Callable case samples
    - Callable control samples
    - Case carriers
    - Control carriers
    - Case non-carriers
    - Control non-carriers
    - Missing case genotypes
    - Missing control genotypes
    - Fisher's exact test P-value
    - Chi-square P-value
    - Odds ratio
    - 95% confidence interval
    - Association status
    - Association note
    """

    # -----------------------------------------------------
    # Retrieve genotype calls for this variant
    # -----------------------------------------------------

    variant_genotypes = get_variant_genotypes(
        row,
        genotype_df
    )

    # -----------------------------------------------------
    # Restrict to phenotype groups
    # -----------------------------------------------------

    case_genotypes = variant_genotypes[
        variant_genotypes["Sample"].isin(
            case_samples
        )
    ].copy()

    control_genotypes = variant_genotypes[
        variant_genotypes["Sample"].isin(
            control_samples
        )
    ].copy()

    # -----------------------------------------------------
    # Callable sample counts
    # -----------------------------------------------------

    case_callable = (
        case_genotypes["Sample"]
        .nunique()
    )

    control_callable = (
        control_genotypes["Sample"]
        .nunique()
    )

    # -----------------------------------------------------
    # Runtime warning for non-estimable control group
    #
    # A variant with no callable control genotypes cannot
    # support inferential case-control association analysis.
    # The pipeline continues, but the result is explicitly
    # flagged as "Not estimable" below.
    # -----------------------------------------------------
    if control_callable == 0:
        variant_label = row.get(
            "HGVS_cDNA",
            "unknown variant"
        )

        print(
            "WARNING: No callable control genotypes were "
            f"available for {variant_label}. "
            "Association statistics are not inferentially "
            "estimable."
        )

    # -----------------------------------------------------
    # Carrier counts
    #
    # Genotype:
    #   0 = homozygous reference
    #   1 = heterozygous
    #   2 = homozygous variant
    #
    # Any genotype > 0 represents a carrier of the
    # alternate allele.
    # -----------------------------------------------------

    case_carriers = (
        case_genotypes[
            case_genotypes["Genotype"] > 0
        ]["Sample"]
        .nunique()
    )

    control_carriers = (
        control_genotypes[
            control_genotypes["Genotype"] > 0
        ]["Sample"]
        .nunique()
    )

    # -----------------------------------------------------
    # Non-carriers
    # -----------------------------------------------------

    case_noncarriers = (
        case_genotypes[
            case_genotypes["Genotype"] == 0
        ]["Sample"]
        .nunique()
    )

    control_noncarriers = (
        control_genotypes[
            control_genotypes["Genotype"] == 0
        ]["Sample"]
        .nunique()
    )

    # -----------------------------------------------------
    # Missing genotype counts
    #
    # Missing calls are not interpreted as non-carriers.
    # -----------------------------------------------------

    case_missing = max(
        0,
        len(case_samples) - case_callable
    )

    control_missing = max(
        0,
        len(control_samples) - control_callable
    )

    # -----------------------------------------------------
    # 2 × 2 contingency table
    # -----------------------------------------------------

    table = np.array([
        [
            case_carriers,
            case_noncarriers
        ],
        [
            control_carriers,
            control_noncarriers
        ]
    ])

    # -----------------------------------------------------
    # Determine whether association is estimable
    # -----------------------------------------------------

    if case_callable == 0 and control_callable == 0:

        association_status = "Not estimable"

        association_note = (
            "No callable case or control genotypes "
            "available after quality filtering."
        )

    elif case_callable == 0:

        association_status = "Not estimable"

        association_note = (
            "No callable case genotypes available "
            "after quality filtering."
        )

    elif control_callable == 0:

        association_status = "Not estimable"

        association_note = (
            "No callable control genotypes available "
            "after quality filtering."
        )

    elif (
        case_carriers == 0
        and control_carriers == 0
    ):

        association_status = "No observed carriers"

        association_note = (
            "No alternate-allele carriers among "
            "callable case or control genotypes."
        )

    else:

        association_status = "Estimable"

        association_note = ""

    # -----------------------------------------------------
    # Fisher's exact test
    #
    # Fisher's exact test remains the primary association
    # test, particularly for sparse genotype counts.
    # -----------------------------------------------------

    try:

        _, fisher_p = fisher_exact(
            table
        )

    except Exception:

        fisher_p = np.nan

    # -----------------------------------------------------
    # Chi-square test
    #
    # This is reported as a supplementary statistic.
    # Fisher's exact test remains the preferred test when
    # cell counts are small.
    # -----------------------------------------------------

    try:

        _, chi_p, _, _ = chi2_contingency(
            table,
            correction=False
        )

    except Exception:

        chi_p = np.nan

    # -----------------------------------------------------
    # Odds ratio + 95% CI
    #
    # Explicitly request the zero-cell correction in
    # statsmodels for stable estimation when a cell is zero.
    #
    # Important:
    # The corrected OR is retained for descriptive
    # reporting, but a zero-callable group is flagged as
    # "Not estimable" above.
    # -----------------------------------------------------

    try:

        table_2x2 = Table2x2(
            table,
            shift_zeros=True
        )

        odds_ratio = (
            table_2x2.oddsratio
        )

        ci_low, ci_high = (
            table_2x2.oddsratio_confint()
        )

    except Exception:

        odds_ratio = np.nan

        ci_low = np.nan

        ci_high = np.nan

    # -----------------------------------------------------
    # Return results
    # -----------------------------------------------------

    return {
        **row.to_dict(),

        "Case_Callable": case_callable,

        "Control_Callable": control_callable,

        "Case_Missing": case_missing,

        "Control_Missing": control_missing,

        "Case_Carriers": case_carriers,

        "Control_Carriers": control_carriers,

        "Case_NonCarriers": case_noncarriers,

        "Control_NonCarriers": control_noncarriers,

        "Total_Callable": (
            case_callable
            + control_callable
        ),

        "Total_Missing": (
            case_missing
            + control_missing
        ),

        "Odds_Ratio": odds_ratio,

        "CI_Lower": ci_low,

        "CI_Upper": ci_high,

        "Fisher_P": fisher_p,

        "ChiSquare_P": chi_p,

        "Association_Status": association_status,

        "Association_Note": association_note
    }


# =========================================================
# Run association analysis
# =========================================================


def run_association_analysis(
    final_df: pd.DataFrame,
    genotype_df: pd.DataFrame,
    case_samples,
    control_samples,
    min_phred: int = 20
) -> pd.DataFrame:
    """
    Perform case-control association analysis
    for every validated variant.

    Association denominators are determined separately
    for each variant using samples with valid,
    high-confidence genotype calls at that position.

    Samples lacking callable genotypes at a variant are
    treated as missing for that variant.

    Parameters
    ----------
    final_df : pandas.DataFrame
        Final annotated variant table.

    genotype_df : pandas.DataFrame
        Genotype calls generated by the pipeline.

    case_samples : set
        Case sample IDs.

    control_samples : set
        Control sample IDs.

    min_phred : int, default=20
        Minimum Phred quality for callable genotypes.

    Returns
    -------
    pandas.DataFrame
        Association analysis results.
    """

    if final_df.empty:
        return pd.DataFrame()

    genotype_df = prepare_genotype_data(
        genotype_df,
        min_phred=min_phred
    )

    results = []

    for _, row in final_df.iterrows():

        results.append(
            analyse_variant(
                row,
                genotype_df,
                case_samples,
                control_samples
            )
        )

    return pd.DataFrame(
        results
    )


# =========================================================
# Multiple-testing correction
# =========================================================


def apply_multiple_testing(
    association_df: pd.DataFrame
) -> pd.DataFrame:
    """
    Apply Benjamini-Hochberg FDR correction
    to Fisher's exact test P-values.

    Parameters
    ----------
    association_df : pandas.DataFrame
        Association analysis results.

    Returns
    -------
    pandas.DataFrame
        Association results with FDR-adjusted P-values.
    """

    association_df = association_df.copy()

    if association_df.empty:

        association_df["FDR_P"] = pd.Series(
            dtype=float
        )

        association_df["Significant_FDR"] = (
            pd.Series(dtype=bool)
        )

        return association_df

    valid_p = (
        association_df["Fisher_P"]
        .notna()
    )

    association_df["FDR_P"] = np.nan

    if valid_p.any():

        association_df.loc[
            valid_p,
            "FDR_P"
        ] = multipletests(
            association_df.loc[
                valid_p,
                "Fisher_P"
            ],
            method="fdr_bh"
        )[1]

    association_df["Significant_FDR"] = (
        association_df["FDR_P"] < 0.05
    )

    return association_df


# =========================================================
# Reorder association columns
# =========================================================


def reorder_association_columns(
    association_df: pd.DataFrame
) -> pd.DataFrame:
    """
    Reorder association results into a consistent
    reporting structure.

    Columns not present in the input dataframe are omitted.
    """

    preferred_columns = [

        "Gene",

        "Transcript",

        "Transcript_Position",

        "HGVS_cDNA_Position",

        "HGVS_cDNA",

        "Chromosome",

        "Genomic_Position",

        "REF",

        "ALT",

        "Consequence",

        "Impact",

        "Case_Callable",

        "Control_Callable",

        "Case_Missing",

        "Control_Missing",

        "Case_Carriers",

        "Control_Carriers",

        "Case_NonCarriers",

        "Control_NonCarriers",

        "Total_Callable",

        "Total_Missing",

        "Odds_Ratio",

        "CI_Lower",

        "CI_Upper",

        "Fisher_P",

        "ChiSquare_P",

        "FDR_P",

        "Significant_FDR",

        "Association_Status",

        "Association_Note"
    ]

    available_columns = [
        column
        for column in preferred_columns
        if column in association_df.columns
    ]

    remaining_columns = [
        column
        for column in association_df.columns
        if column not in available_columns
    ]

    return association_df[
        available_columns
        + remaining_columns
    ]


# =========================================================
# Sort association results
# =========================================================


def sort_association_results(
    association_df: pd.DataFrame
) -> pd.DataFrame:
    """
    Sort variants by Fisher's exact test P-value
    and odds ratio.

    Missing P-values are placed last.
    """

    if association_df.empty:
        return association_df

    return association_df.sort_values(
        by=[
            "Fisher_P",
            "Odds_Ratio"
        ],
        ascending=[
            True,
            False
        ],
        na_position="last"
    ).reset_index(
        drop=True
    )


# =========================================================
# Save association results
# =========================================================


def save_association_results(
    association_df: pd.DataFrame,
    output_folder: str
) -> str:
    """
    Save association analysis results.

    Parameters
    ----------
    association_df : pandas.DataFrame
        Association analysis results.

    output_folder : str
        Directory in which to save the results.

    Returns
    -------
    str
        Path to the saved association results file.
    """

    os.makedirs(
        output_folder,
        exist_ok=True
    )

    output_file = os.path.join(
        output_folder,
        "ASS1_Association_Analysis.csv"
    )

    association_df.to_csv(
        output_file,
        index=False
    )

    return output_file