"""
final_table.py

Build the final annotated variant table.

This module combines:

1. HGVS variant definitions
2. Confirmed genotype calls
3. Functional annotation generated by the annotation module

Important design principle
--------------------------
Genotype-derived information is authoritative for:

- Carrier_Count
- Variant_Frequency
- Samples

VEP/Ensembl annotation is used only for functional,
gene, transcript, consequence and database annotation.

The module is gene-agnostic and does not contain
gene-specific assumptions.
"""

from pathlib import Path

import numpy as np
import pandas as pd


# ============================================================
# HELPER FUNCTIONS
# ============================================================

def clean_string(value):
    """
    Convert a value to a clean string.

    Missing or empty values are represented by '-'.
    """

    if pd.isna(value):
        return "-"

    value = str(value).strip()

    if not value:
        return "-"

    if value.lower() in {
        "nan",
        "none",
        "null",
        "na",
        "n/a",
    }:
        return "-"

    return value


def normalise_hgvs(value):
    """
    Normalise HGVS strings by removing whitespace.

    Example
    -------
    NM_000050.4:c. 783T>C

    becomes

    NM_000050.4:c.783T>C
    """

    if pd.isna(value):
        return ""

    value = str(value).strip()

    return "".join(value.split())


def normalise_sample(value):
    """
    Normalise sample identifiers.

    Example
    -------
    A5. ab1

    becomes

    A5.ab1
    """

    if pd.isna(value):
        return ""

    return str(value).strip().replace(" ", "")


def to_numeric(value):
    """
    Safely convert a value to numeric.
    """

    return pd.to_numeric(
        value,
        errors="coerce",
    )


def is_true(value):
    """
    Convert common TRUE/FALSE representations
    into a Python boolean.
    """

    if isinstance(value, bool):
        return value

    if pd.isna(value):
        return False

    value = str(value).strip().lower()

    return value in {
        "true",
        "1",
        "yes",
        "y",
    }


# ============================================================
# BUILD FINAL VARIANT TABLE
# ============================================================

def build_final_variant_table(
    hgvs_df: pd.DataFrame,
    genotype_df: pd.DataFrame,
    annotation_df: pd.DataFrame,
) -> pd.DataFrame:
    """
    Build the final annotated variant table.

    Parameters
    ----------
    hgvs_df : pandas.DataFrame
        HGVS variant table generated by the HGVS module.

    genotype_df : pandas.DataFrame
        Genotype table generated by the genotype module.

    annotation_df : pandas.DataFrame
        Annotation table generated by annotation.py.

    Returns
    -------
    pandas.DataFrame
        Final publication-ready variant table.

    Notes
    -----
    Genotype information is used as the authoritative source
    for carrier counts, carrier frequency and carrier samples.

    Annotation information is used only for annotation.
    """

    print()
    print("=" * 70)
    print("BUILDING FINAL ANNOTATED VARIANT TABLE")
    print("=" * 70)
    print()

    # ========================================================
    # 1. VALIDATE INPUT DATAFRAMES
    # ========================================================

    if hgvs_df is None or hgvs_df.empty:
        raise ValueError(
            "HGVS table is empty. "
            "No final variants are available."
        )

    if genotype_df is None or genotype_df.empty:
        raise ValueError(
            "Genotype table is empty. "
            "Cannot determine confirmed carriers."
        )

    if annotation_df is None:
        raise ValueError(
            "Annotation dataframe is None. "
            "Functional annotation must be generated "
            "before building the final variant table."
        )

    # Work on copies so the original dataframes are not modified.
    hgvs_df = hgvs_df.copy()
    genotype_df = genotype_df.copy()
    annotation_df = annotation_df.copy()

    # ========================================================
    # 2. NORMALISE COLUMN NAMES
    # ========================================================

    hgvs_df.columns = (
        hgvs_df.columns
        .astype(str)
        .str.strip()
    )

    genotype_df.columns = (
        genotype_df.columns
        .astype(str)
        .str.strip()
    )

    annotation_df.columns = (
        annotation_df.columns
        .astype(str)
        .str.strip()
    )

    # ========================================================
    # 3. VALIDATE HGVS TABLE
    # ========================================================

    required_hgvs_columns = [
        "Transcript",
        "Transcript_Position",
        "HGVS_cDNA",
        "REF",
        "ALT",
    ]

    missing_hgvs = [
        column
        for column in required_hgvs_columns
        if column not in hgvs_df.columns
    ]

    if missing_hgvs:
        raise KeyError(
            "HGVS dataframe is missing required columns:\n"
            + "\n".join(
                f"  - {column}"
                for column in missing_hgvs
            )
        )

    # ========================================================
    # 4. NORMALISE HGVS VARIANTS
    # ========================================================

    hgvs_df["HGVS_NORMALISED"] = (
        hgvs_df["HGVS_cDNA"]
        .apply(normalise_hgvs)
    )

    hgvs_df = hgvs_df[
        hgvs_df["HGVS_NORMALISED"] != ""
    ].copy()

    hgvs_df = (
        hgvs_df
        .drop_duplicates(
            subset=["HGVS_NORMALISED"],
            keep="first",
        )
        .reset_index(drop=True)
    )

    print(
        f"HGVS variants found: {len(hgvs_df)}"
    )

    # ========================================================
    # 5. VALIDATE GENOTYPE TABLE
    # ========================================================

    required_genotype_columns = [
        "Sample",
        "cDNA_Position",
        "REF",
        "ALT",
        "Is_Variant",
    ]

    missing_genotype = [
        column
        for column in required_genotype_columns
        if column not in genotype_df.columns
    ]

    if missing_genotype:
        raise KeyError(
            "Genotype dataframe is missing required columns:\n"
            + "\n".join(
                f"  - {column}"
                for column in missing_genotype
            )
        )

    print(
        f"Genotype records loaded: {len(genotype_df)}"
    )

    # ========================================================
    # 6. NORMALISE GENOTYPE DATA
    # ========================================================

    genotype_df["Sample_Clean"] = (
        genotype_df["Sample"]
        .apply(normalise_sample)
    )

    genotype_df["cDNA_Position_Numeric"] = (
        genotype_df["cDNA_Position"]
        .apply(to_numeric)
    )

    genotype_df["REF_Clean"] = (
        genotype_df["REF"]
        .apply(clean_string)
        .str.upper()
    )

    genotype_df["ALT_Clean"] = (
        genotype_df["ALT"]
        .apply(clean_string)
        .str.upper()
    )

    genotype_df["Is_Variant_Clean"] = (
        genotype_df["Is_Variant"]
        .apply(is_true)
    )

    # ========================================================
    # 7. SELECT CONFIRMED VARIANT CALLS
    # ========================================================

    confirmed_genotypes = genotype_df[
        genotype_df["Is_Variant_Clean"]
    ].copy()

    # --------------------------------------------------------
    # Exclude ambiguous/low-confidence calls
    # --------------------------------------------------------

    if "Confidence" in confirmed_genotypes.columns:

        confidence = (
            confirmed_genotypes["Confidence"]
            .astype(str)
            .str.strip()
            .str.lower()
        )

        excluded_confidence = confidence.isin({
            "ambiguous_het",
            "lowconfidence_heterozygous",
            "low confidence heterozygous",
        })

        confirmed_genotypes = (
            confirmed_genotypes[
                ~excluded_confidence
            ]
            .copy()
        )

    # --------------------------------------------------------
    # Exclude low-confidence zygosity
    # --------------------------------------------------------

    if "Zygosity" in confirmed_genotypes.columns:

        zygosity = (
            confirmed_genotypes["Zygosity"]
            .astype(str)
            .str.strip()
            .str.lower()
        )

        low_confidence_zygosity = (
            zygosity.str.contains(
                "lowconfidence",
                na=False,
            )
            |
            zygosity.str.contains(
                "low confidence",
                na=False,
            )
        )

        confirmed_genotypes = (
            confirmed_genotypes[
                ~low_confidence_zygosity
            ]
            .copy()
        )

    print(
        f"Confirmed genotype calls: "
        f"{len(confirmed_genotypes)}"
    )

    # ========================================================
    # 8. DETERMINE TOTAL SAMPLE COUNT
    # ========================================================

    all_samples = (
        genotype_df["Sample_Clean"]
        .replace("", np.nan)
        .dropna()
        .drop_duplicates()
        .tolist()
    )

    total_samples = len(all_samples)

    if total_samples == 0:
        raise ValueError(
            "No sample identifiers were found "
            "in the genotype table."
        )

    print(
        f"Total samples detected: {total_samples}"
    )

    # ========================================================
    # 9. BUILD CARRIER SUMMARY
    # ========================================================

    print()
    print(
        "Matching HGVS variants to confirmed "
        "genotype carriers..."
    )
    print()

    carrier_records = []

    for _, hgvs_row in hgvs_df.iterrows():

        hgvs = hgvs_row["HGVS_NORMALISED"]

        ref = (
            clean_string(
                hgvs_row["REF"]
            )
            .upper()
        )

        alt = (
            clean_string(
                hgvs_row["ALT"]
            )
            .upper()
        )

        transcript_position = (
            to_numeric(
                hgvs_row["Transcript_Position"]
            )
        )

        if pd.isna(transcript_position):

            raise ValueError(
                f"Missing Transcript_Position "
                f"for {hgvs}"
            )

        # ----------------------------------------------------
        # Position matching
        #
        # HGVS_Table.Transcript_Position
        #        =
        # Genotype_Table.cDNA_Position
        # ----------------------------------------------------

        position_matches = (
            confirmed_genotypes[
                confirmed_genotypes[
                    "cDNA_Position_Numeric"
                ]
                == transcript_position
            ]
            .copy()
        )

        # ----------------------------------------------------
        # REF matching
        # ----------------------------------------------------

        position_matches = (
            position_matches[
                position_matches["REF_Clean"]
                == ref
            ]
            .copy()
        )

        # ----------------------------------------------------
        # ALT matching
        # ----------------------------------------------------

        position_matches = (
            position_matches[
                position_matches["ALT_Clean"]
                == alt
            ]
            .copy()
        )

        # ----------------------------------------------------
        # Unique confirmed carriers
        # ----------------------------------------------------

        carriers = (
            position_matches[
                "Sample_Clean"
            ]
            .replace("", np.nan)
            .dropna()
            .drop_duplicates()
            .tolist()
        )

        carrier_count = len(carriers)

        variant_frequency = (
            carrier_count / total_samples
        )

        samples_string = ";".join(
            carriers
        )

        print(
            f"{hgvs}: "
            f"{carrier_count} carrier(s) -> "
            f"{samples_string if samples_string else 'None'}"
        )

        carrier_records.append({

            # --------------------------------------------------------
            # Internal merge key
            # --------------------------------------------------------

            "HGVS_NORMALISED": hgvs,

            # --------------------------------------------------------
            # Variant identity
            # --------------------------------------------------------

            "HGVS_cDNA": hgvs,

            "REF": ref,

            "ALT": alt,

            # --------------------------------------------------------
            # Coordinate information
            #
            # IMPORTANT:
            # Transcript_Position is required downstream by HWE.
            # It corresponds to cDNA_Position in Genotype_Table.csv.
            # --------------------------------------------------------

            "Transcript": clean_string(
                hgvs_row["Transcript"]
            ),

            "Transcript_Position": int(
                transcript_position
            ),

            "HGVS_cDNA_Position": to_numeric(
                hgvs_row["HGVS_cDNA_Position"]
            ),

            # --------------------------------------------------------
            # Genotype-derived information
            # --------------------------------------------------------

            "Carrier_Count": carrier_count,

            "Variant_Frequency": variant_frequency,

            "Samples": samples_string,

        })

    carrier_df = pd.DataFrame(
        carrier_records
    )

    # ========================================================
    # 10. VALIDATE CARRIER SUMMARY
    # ========================================================

    required_carrier_columns = [
        "HGVS_NORMALISED",
        "HGVS_cDNA",
        "REF",
        "ALT",
        "Carrier_Count",
        "Variant_Frequency",
        "Samples",
    ]

    missing_carrier = [
        column
        for column in required_carrier_columns
        if column not in carrier_df.columns
    ]

    if missing_carrier:
        raise RuntimeError(
            "Internal carrier summary is missing:\n"
            + "\n".join(
                f"  - {column}"
                for column in missing_carrier
            )
        )

    # ========================================================
    # 11. PREPARE VEP/ENSEMBL ANNOTATION
    # ========================================================

    print()
    print("Loading Ensembl VEP annotation...")

    if annotation_df.empty:

        print(
            "Warning: annotation dataframe is empty. "
            "Final table will contain genotype information "
            "but no functional annotation."
        )

        vep_unique = pd.DataFrame(
            columns=["HGVS_NORMALISED"]
        )

    else:

        # ----------------------------------------------------
        # Identify HGVS column
        # ----------------------------------------------------

        annotation_hgvs_candidates = [
            "HGVS_cDNA",
            "#Uploaded_variation",
            "Uploaded_variation",
        ]

        annotation_hgvs_column = None

        for column in annotation_hgvs_candidates:

            if column in annotation_df.columns:

                annotation_hgvs_column = column

                break

        if annotation_hgvs_column is None:

            raise KeyError(
                "Could not identify the HGVS column "
                "in the annotation dataframe.\n\n"
                "Expected one of:\n"
                +
                "\n".join(
                    f"  - {column}"
                    for column in
                    annotation_hgvs_candidates
                )
            )

        annotation_df["HGVS_NORMALISED"] = (
            annotation_df[
                annotation_hgvs_column
            ]
            .apply(normalise_hgvs)
        )

        vep_unique = (
            annotation_df[
                annotation_df[
                    "HGVS_NORMALISED"
                ] != ""
            ]
            .drop_duplicates(
                subset=[
                    "HGVS_NORMALISED"
                ],
                keep="first",
            )
            .copy()
        )

    # ========================================================
    # 12. CHECK VEP MATCHING
    # ========================================================

    matched_vep = (
        carrier_df[
            ["HGVS_NORMALISED"]
        ]
        .merge(
            vep_unique[
                ["HGVS_NORMALISED"]
            ],
            on="HGVS_NORMALISED",
            how="left",
            indicator=True,
        )
    )

    vep_match_count = (
        matched_vep["_merge"]
        .eq("both")
        .sum()
    )

    print(
        "VEP HGVS matching: "
        f"{vep_match_count} of "
        f"{len(carrier_df)} variants matched."
    )

    # ========================================================
    # 13. MERGE ANNOTATION WITH CARRIER SUMMARY
    # ========================================================

    final_df = carrier_df.merge(
        vep_unique,
        on="HGVS_NORMALISED",
        how="left",
        suffixes=(
            "",
            "_VEP",
        ),
    )

    # ========================================================
    # 14. REMOVE CONFLICTING ANNOTATION FIELDS
    # ========================================================

    # These fields are always derived from the genotype data.

    conflicting_columns = [

        "Carrier_Count_VEP",
        "Variant_Carrier_Count",

        "Variant_Frequency_VEP",

        "Samples_VEP",

        "Variant_Calls",
        "Variant_Samples",

        "Genotype_Calls",
        "Genotype_Sample_Count",
    ]

    for column in conflicting_columns:

        if column in final_df.columns:

            final_df.drop(
                columns=[column],
                inplace=True,
            )

    # ========================================================
    # 15. REMOVE INTERNAL ANNOTATION IDENTIFIERS
    # ========================================================

    for column in [
        "#Uploaded_variation",
        "Uploaded_variation",
    ]:

        if column in final_df.columns:

            final_df.drop(
                columns=[column],
                inplace=True,
            )

    # ========================================================
    # 16. PROTECT CORE GENOTYPE INFORMATION
    # ========================================================

    core_genotype_fields = carrier_df[
        [
            "HGVS_cDNA",
            "Carrier_Count",
            "Variant_Frequency",
            "Samples",
        ]
    ].copy()

    for column in [
        "Carrier_Count",
        "Variant_Frequency",
        "Samples",
    ]:

        if column in final_df.columns:

            final_df.drop(
                columns=[column],
                inplace=True,
            )

    final_df = final_df.merge(
        core_genotype_fields,
        on="HGVS_cDNA",
        how="left",
    )

    # ========================================================
    # 17. PROTECT REF / ALT
    # ========================================================

    hgvs_core = hgvs_df[
        [
            "HGVS_NORMALISED",
            "REF",
            "ALT",
        ]
    ].copy()

    hgvs_core["HGVS_cDNA"] = (
        hgvs_core["HGVS_NORMALISED"]
    )

    hgvs_core = hgvs_core[
        [
            "HGVS_cDNA",
            "REF",
            "ALT",
        ]
    ]

    for column in [
        "REF",
        "ALT",
    ]:

        if column in final_df.columns:

            final_df.drop(
                columns=[column],
                inplace=True,
            )

    final_df = final_df.merge(
        hgvs_core,
        on="HGVS_cDNA",
        how="left",
    )

    # ========================================================
    # 18. VARIANT TYPE
    # ========================================================

    if "Variant_Type" not in final_df.columns:

        final_df["Variant_Type"] = np.where(
            (
                final_df["REF"].str.len() == 1
            )
            &
            (
                final_df["ALT"].str.len() == 1
            ),
            "SNV",
            "Other",
        )

    # ========================================================
    # 19. REORDER COLUMNS
    # ========================================================

    preferred_order = [

        # Variant identity
        "HGVS_cDNA",
        "REF",
        "ALT",
        "Variant_Type",

        # Functional annotation
        "Consequence",
        "Impact",
        "Most_Severe_Consequence",
        "Protein_HGVS",
        "Protein_Position",
        "Amino_Acid_Change",
        "Codon_Change",

        # Gene annotation
        "Gene",
        "Gene_ID",
        "SYMBOL",
        "Transcript",
        "Feature",
        "BIOTYPE",

        # Genomic annotation
        "Assembly",
        "Chromosome",
        "Genomic_Position",
        "End_Position",
        "Strand",
        "Genomic_Coordinate",
        "HGVS_Genomic",

        # Database annotation
        "dbSNP_rsID",
        "Existing_variation",
        "COSMIC_ID",
        "ClinVar_ID",
        "HGMD_ID",

        # Position annotation
        "Transcript_Position",
        "cDNA_Position",
        "CDS_Position",
        "HGVS_cDNA_Position",

        # Genotype-derived information
        "Carrier_Count",
        "Variant_Frequency",
        "Samples",

        # Annotation status
        "Status",

        # Quality
        "Mean_Quality",
        "Mean_Alignment_Score",
    ]

    existing_preferred = [
        column
        for column in preferred_order
        if column in final_df.columns
    ]

    remaining_columns = [
        column
        for column in final_df.columns
        if column not in existing_preferred
        and column != "HGVS_NORMALISED"
    ]

    final_df = final_df[
        existing_preferred
        + remaining_columns
    ]

    # ========================================================
    # 20. REMOVE INTERNAL MERGE KEY
    # ========================================================

    if "HGVS_NORMALISED" in final_df.columns:

        final_df.drop(
            columns=["HGVS_NORMALISED"],
            inplace=True,
        )

    # ========================================================
    # 21. FORMAT NUMERIC FIELDS
    # ========================================================

    if "Carrier_Count" in final_df.columns:

        final_df["Carrier_Count"] = (
            pd.to_numeric(
                final_df["Carrier_Count"],
                errors="coerce",
            )
            .fillna(0)
            .astype(int)
        )

    if "Variant_Frequency" in final_df.columns:

        final_df["Variant_Frequency"] = (
            pd.to_numeric(
                final_df["Variant_Frequency"],
                errors="coerce",
            )
        )

    # ========================================================
    # 22. VALIDATE VARIANT COUNT
    # ========================================================

    if len(final_df) != len(hgvs_df):

        raise RuntimeError(
            "\nFINAL VARIANT COUNT ERROR\n"
            f"HGVS variants: {len(hgvs_df)}\n"
            f"Final variants: {len(final_df)}\n"
        )

    # ========================================================
    # 23. VALIDATE HGVS IDENTITY AND ORDER
    # ========================================================

    expected_hgvs = (
        hgvs_df[
            "HGVS_NORMALISED"
        ]
        .tolist()
    )

    final_hgvs = (
        final_df[
            "HGVS_cDNA"
        ]
        .apply(normalise_hgvs)
        .tolist()
    )

    if expected_hgvs != final_hgvs:

        raise RuntimeError(
            "\nHGVS ORDER/IDENTITY ERROR\n\n"
            f"Expected:\n{expected_hgvs}\n\n"
            f"Final:\n{final_hgvs}\n"
        )

    # ========================================================
    # 24. VALIDATE CARRIER COUNTS AND FREQUENCIES
    # ========================================================

    print()
    print("=" * 70)
    print("FINAL CARRIER SUMMARY")
    print("=" * 70)
    print()

    for _, row in final_df.iterrows():

        hgvs = row["HGVS_cDNA"]

        carrier_count = int(
            row["Carrier_Count"]
        )

        frequency = float(
            row["Variant_Frequency"]
        )

        samples = (
            ""
            if pd.isna(row["Samples"])
            else str(row["Samples"])
        )

        if samples in {
            "",
            "-",
            "nan",
        }:

            sample_list = []

        else:

            sample_list = [
                sample.strip()
                for sample in samples.split(";")
                if sample.strip()
            ]

        sample_count = len(
            sample_list
        )

        print(hgvs)

        print(
            f"  REF: {row['REF']}"
        )

        print(
            f"  ALT: {row['ALT']}"
        )

        print(
            f"  Carrier_Count: "
            f"{carrier_count}"
        )

        print(
            f"  Variant_Frequency: "
            f"{frequency:.3f}"
        )

        print(
            f"  Samples: "
            f"{samples if samples else 'None'}"
        )

        print()

        # ----------------------------------------------------
        # Carrier count validation
        # ----------------------------------------------------

        if carrier_count != sample_count:

            raise RuntimeError(
                f"\nCARRIER COUNT ERROR for {hgvs}\n"
                f"Carrier_Count = {carrier_count}\n"
                f"Number of Samples = {sample_count}\n"
                f"Samples = {samples}\n"
            )

        # ----------------------------------------------------
        # Frequency validation
        # ----------------------------------------------------

        expected_frequency = (
            carrier_count / total_samples
        )

        if not np.isclose(
            frequency,
            expected_frequency,
            atol=1e-9,
        ):

            raise RuntimeError(
                f"\nFREQUENCY ERROR for {hgvs}\n"
                f"Carrier_Count = {carrier_count}\n"
                f"Total samples = {total_samples}\n"
                f"Expected frequency = "
                f"{expected_frequency}\n"
                f"Observed frequency = "
                f"{frequency}\n"
            )

    # ========================================================
    # 25. FINAL DISPLAY
    # ========================================================

    print("=" * 70)
    print("FINAL VARIANT TABLE")
    print("=" * 70)
    print()

    display_columns = [

        "HGVS_cDNA",
        "REF",
        "ALT",
        "Consequence",
        "Impact",
        "Carrier_Count",
        "Variant_Frequency",
        "Samples",
    ]

    available_display_columns = [
        column
        for column in display_columns
        if column in final_df.columns
    ]

    print(
        final_df[
            available_display_columns
        ].to_string(
            index=False,
        )
    )

    print()

    return final_df


# ============================================================
# SAVE FINAL TABLE
# ============================================================

def save_final_table(
    final_df: pd.DataFrame,
    output_folder: str,
) -> str:
    """
    Save the final annotated variant table.

    Parameters
    ----------
    final_df : pandas.DataFrame
        Final variant dataframe.

    output_folder : str
        Directory where the table will be saved.

    Returns
    -------
    str
        Path to the saved CSV file.
    """

    output_path = Path(
        output_folder
    )

    output_path.mkdir(
        parents=True,
        exist_ok=True,
    )

    output_file = (
        output_path
        / "Final_Annotated_Variants.csv"
    )

    final_df.to_csv(
        output_file,
        index=False,
    )

    print(
        "=" * 70
    )

    print(
        "Final variant table saved to:"
    )

    print(
        output_file
    )

    print()

    print(
        f"Final number of variants: "
        f"{len(final_df)}"
    )

    print()

    return str(output_file)