"""
final_table.py

Build the final annotated variant table.

This module combines:

1. HGVS variant definitions
2. Confirmed genotype calls
3. Functional annotation generated by the annotation module

Important design principle
--------------------------
Genotype-derived information is authoritative for:

- Carrier_Count
- Variant_Frequency
- Samples

The confirmed variant table generated after high-confidence filtering
defines which variants are eligible for inclusion.

VEP/Ensembl annotation is used only for:

- functional consequence
- impact
- gene
- transcript
- genomic annotation
- database identifiers

The module is gene-agnostic and does not contain gene-specific
assumptions.
"""

from pathlib import Path

import numpy as np
import pandas as pd


# ============================================================
# HELPER FUNCTIONS
# ============================================================

def clean_string(value):
    """
    Convert a value to a clean string.

    Missing or empty values are represented by '-'.
    """
    if pd.isna(value):
        return "-"

    value = str(value).strip()

    if not value:
        return "-"

    if value.lower() in {
        "nan",
        "none",
        "null",
        "na",
        "n/a",
    }:
        return "-"

    return value


def normalise_hgvs(value):
    """
    Normalise HGVS strings by removing whitespace.

    Example
    -------
    NM_000050.4:c. 783T>C

    becomes

    NM_000050.4:c.783T>C
    """
    if pd.isna(value):
        return ""

    value = str(value).strip()

    return "".join(value.split())


def normalise_sample(value):
    """
    Normalise sample identifiers.

    Example
    -------
    A5. ab1

    becomes

    A5.ab1
    """
    if pd.isna(value):
        return ""

    return str(value).strip().replace(" ", "")


def to_numeric(value):
    """
    Safely convert a value to numeric.
    """
    return pd.to_numeric(
        value,
        errors="coerce",
    )


def is_true(value):
    """
    Convert common TRUE/FALSE representations
    into a Python boolean.
    """
    if isinstance(value, bool):
        return value

    if pd.isna(value):
        return False

    value = str(value).strip().lower()

    return value in {
        "true",
        "1",
        "yes",
        "y",
    }


def normalise_variant_allele(value):
    """
    Normalise a REF or ALT allele.
    """
    return clean_string(value).upper()


def build_variant_key(position, ref, alt):
    """
    Build a stable sample-level variant identity key.

    The key is based on transcript position, REF and ALT.

    This is deliberately independent of HGVS formatting because
    genotype tables use transcript coordinates while HGVS cDNA
    coordinates are CDS-relative.
    """
    position = to_numeric(position)

    if pd.isna(position):
        return None

    ref = normalise_variant_allele(ref)
    alt = normalise_variant_allele(alt)

    if ref == "-" or alt == "-":
        return None

    return (
        int(position),
        ref,
        alt,
    )


# ============================================================
# BUILD FINAL VARIANT TABLE
# ============================================================

def build_final_variant_table(
    hgvs_df: pd.DataFrame,
    genotype_df: pd.DataFrame,
    annotation_df: pd.DataFrame,
    confirmed_variant_df: pd.DataFrame,
    min_phred: float = 20,
) -> pd.DataFrame:
    """
    Build the final annotated variant table.

    Parameters
    ----------
    hgvs_df : pandas.DataFrame
        HGVS variant table generated by the HGVS module.

    genotype_df : pandas.DataFrame
        Complete sample-level genotype table generated by the
        genotype module.

    annotation_df : pandas.DataFrame
        Annotation table generated by annotation.py.

    confirmed_variant_df : pandas.DataFrame
        Variant-level table produced after high-confidence
        filtering in the genotype module.

        This dataframe defines which variants passed the
        high-confidence filtering stage.

    min_phred : float, default=20
        Minimum Phred quality required for a genotype call to
        contribute to confirmed carrier counts.

    Returns
    -------
    pandas.DataFrame
        Final publication-ready annotated variant table.

    Notes
    -----
    The complete genotype dataframe is retained as the source
    for determining the total sequenced sample universe.

    However, only sample-level genotype calls that:

    1. correspond to a confirmed variant,
    2. have Is_Variant=True,
    3. meet the minimum Phred threshold, and
    4. are not classified as low-confidence/ambiguous

    are counted as confirmed carriers.

    Samples without a callable high-confidence genotype for a
    variant are not classified as non-carriers.
    """

    print()
    print("=" * 70)
    print("BUILDING FINAL ANNOTATED VARIANT TABLE")
    print("=" * 70)
    print()

    # ========================================================
    # 1. VALIDATE INPUT DATAFRAMES
    # ========================================================

    if hgvs_df is None or hgvs_df.empty:
        raise ValueError(
            "HGVS table is empty. "
            "No final variants are available."
        )

    if genotype_df is None or genotype_df.empty:
        raise ValueError(
            "Genotype table is empty. "
            "Cannot determine confirmed carriers."
        )

    if confirmed_variant_df is None or confirmed_variant_df.empty:
        raise ValueError(
            "High-confidence variant table is empty. "
            "Cannot determine confirmed carriers."
        )

    if annotation_df is None:
        raise ValueError(
            "Annotation dataframe is None. "
            "Functional annotation must be generated "
            "before building the final variant table."
        )

    # Work on copies so the original dataframes are not modified.
    hgvs_df = hgvs_df.copy()
    genotype_df = genotype_df.copy()
    annotation_df = annotation_df.copy()
    confirmed_variant_df = confirmed_variant_df.copy()

    # ========================================================
    # 2. NORMALISE COLUMN NAMES
    # ========================================================

    for dataframe in [
        hgvs_df,
        genotype_df,
        annotation_df,
        confirmed_variant_df,
    ]:
        dataframe.columns = (
            dataframe.columns
            .astype(str)
            .str.strip()
        )

    # ========================================================
    # 3. VALIDATE HGVS TABLE
    # ========================================================

    required_hgvs_columns = [
        "Transcript",
        "Transcript_Position",
        "HGVS_cDNA",
        "HGVS_cDNA_Position",
        "REF",
        "ALT",
    ]

    missing_hgvs = [
        column
        for column in required_hgvs_columns
        if column not in hgvs_df.columns
    ]

    if missing_hgvs:
        raise KeyError(
            "HGVS dataframe is missing required columns:\n"
            + "\n".join(
                f"  - {column}"
                for column in missing_hgvs
            )
        )

    # ========================================================
    # 4. VALIDATE CONFIRMED VARIANT TABLE
    # ========================================================

    required_confirmed_columns = [
        "cDNA_Position",
        "REF",
        "ALT",
    ]

    missing_confirmed = [
        column
        for column in required_confirmed_columns
        if column not in confirmed_variant_df.columns
    ]

    if missing_confirmed:
        raise KeyError(
            "Confirmed variant dataframe is missing "
            "required columns:\n"
            + "\n".join(
                f"  - {column}"
                for column in missing_confirmed
            )
        )

    # ========================================================
    # 5. NORMALISE HGVS VARIANTS
    # ========================================================

    hgvs_df["HGVS_NORMALISED"] = (
        hgvs_df["HGVS_cDNA"]
        .apply(normalise_hgvs)
    )

    hgvs_df = hgvs_df[
        hgvs_df["HGVS_NORMALISED"] != ""
    ].copy()

    hgvs_df = (
        hgvs_df
        .drop_duplicates(
            subset=["HGVS_NORMALISED"],
            keep="first",
        )
        .reset_index(drop=True)
    )

    print(
        f"HGVS variants found: {len(hgvs_df)}"
    )

    # ========================================================
    # 6. VALIDATE GENOTYPE TABLE
    # ========================================================

    required_genotype_columns = [
        "Sample",
        "cDNA_Position",
        "REF",
        "ALT",
        "Is_Variant",
    ]

    missing_genotype = [
        column
        for column in required_genotype_columns
        if column not in genotype_df.columns
    ]

    if missing_genotype:
        raise KeyError(
            "Genotype dataframe is missing required columns:\n"
            + "\n".join(
                f"  - {column}"
                for column in missing_genotype
            )
        )

    if "Quality" not in genotype_df.columns:
        raise KeyError(
            "Genotype dataframe must contain the 'Quality' "
            "column so that the minimum Phred threshold can "
            "be applied to sample-level genotype calls."
        )

    print(
        f"Genotype records loaded: {len(genotype_df)}"
    )

    # ========================================================
    # 7. NORMALISE GENOTYPE DATA
    # ========================================================

    genotype_df["Sample_Clean"] = (
        genotype_df["Sample"]
        .apply(normalise_sample)
    )

    genotype_df["cDNA_Position_Numeric"] = (
        genotype_df["cDNA_Position"]
        .apply(to_numeric)
    )

    genotype_df["REF_Clean"] = (
        genotype_df["REF"]
        .apply(normalise_variant_allele)
    )

    genotype_df["ALT_Clean"] = (
        genotype_df["ALT"]
        .apply(normalise_variant_allele)
    )

    genotype_df["Is_Variant_Clean"] = (
        genotype_df["Is_Variant"]
        .apply(is_true)
    )

    genotype_df["Quality_Numeric"] = (
        genotype_df["Quality"]
        .apply(to_numeric)
    )

    # ========================================================
    # 8. BUILD CONFIRMED VARIANT KEY SET
    # ========================================================

    confirmed_variant_df["cDNA_Position_Numeric"] = (
        confirmed_variant_df["cDNA_Position"]
        .apply(to_numeric)
    )

    confirmed_variant_df["REF_Clean"] = (
        confirmed_variant_df["REF"]
        .apply(normalise_variant_allele)
    )

    confirmed_variant_df["ALT_Clean"] = (
        confirmed_variant_df["ALT"]
        .apply(normalise_variant_allele)
    )

    confirmed_variant_keys = set()

    for _, row in confirmed_variant_df.iterrows():

        key = build_variant_key(
            row["cDNA_Position_Numeric"],
            row["REF_Clean"],
            row["ALT_Clean"],
        )

        if key is not None:
            confirmed_variant_keys.add(key)

    if not confirmed_variant_keys:
        raise ValueError(
            "No valid variant identities were found in "
            "confirmed_variant_df. Expected valid values in "
            "'cDNA_Position', 'REF', and 'ALT'."
        )

    print(
        "Confirmed high-confidence variants: "
        f"{len(confirmed_variant_keys)}"
    )

    # ========================================================
    # 9. SELECT CONFIRMED SAMPLE-LEVEL GENOTYPE CALLS
    # ========================================================

    print()
    print(
        "Selecting high-confidence sample-level "
        "genotype calls..."
    )
    print()

    confirmed_genotypes = genotype_df[
        genotype_df["Is_Variant_Clean"]
    ].copy()

    initial_variant_calls = len(
        confirmed_genotypes
    )

    # --------------------------------------------------------
    # Apply minimum Phred quality
    # --------------------------------------------------------

    confirmed_genotypes = confirmed_genotypes[
        confirmed_genotypes["Quality_Numeric"]
        >= float(min_phred)
    ].copy()

    after_phred_calls = len(
        confirmed_genotypes
    )

    print(
        f"Variant genotype calls before "
        f"Phred filtering: {initial_variant_calls}"
    )

    print(
        f"Minimum Phred threshold: {min_phred}"
    )

    print(
        f"Variant genotype calls after "
        f"Phred filtering: {after_phred_calls}"
    )

    # --------------------------------------------------------
    # Exclude ambiguous/low-confidence calls
    # --------------------------------------------------------

    if "Confidence" in confirmed_genotypes.columns:

        confidence = (
            confirmed_genotypes["Confidence"]
            .astype(str)
            .str.strip()
            .str.lower()
        )

        excluded_confidence = confidence.isin({
            "ambiguous_het",
            "ambiguous",
            "lowconfidence_heterozygous",
            "low confidence heterozygous",
            "lowconfidence",
            "low confidence",
        })

        confirmed_genotypes = (
            confirmed_genotypes[
                ~excluded_confidence
            ]
            .copy()
        )

    # --------------------------------------------------------
    # Exclude low-confidence zygosity
    # --------------------------------------------------------

    if "Zygosity" in confirmed_genotypes.columns:

        zygosity = (
            confirmed_genotypes["Zygosity"]
            .astype(str)
            .str.strip()
            .str.lower()
        )

        low_confidence_zygosity = (
            zygosity.str.contains(
                "lowconfidence",
                na=False,
            )
            |
            zygosity.str.contains(
                "low confidence",
                na=False,
            )
        )

        confirmed_genotypes = (
            confirmed_genotypes[
                ~low_confidence_zygosity
            ]
            .copy()
        )

    # --------------------------------------------------------
    # Restrict calls to variants that survived Step 9
    # --------------------------------------------------------

    confirmed_genotypes["Variant_Key"] = list(
        map(
            build_variant_key,
            confirmed_genotypes[
                "cDNA_Position_Numeric"
            ],
            confirmed_genotypes[
                "REF_Clean"
            ],
            confirmed_genotypes[
                "ALT_Clean"
            ],
        )
    )

    confirmed_genotypes = confirmed_genotypes[
        confirmed_genotypes["Variant_Key"]
        .isin(confirmed_variant_keys)
    ].copy()

    print(
        "Confirmed sample-level genotype calls: "
        f"{len(confirmed_genotypes)}"
    )

    # ========================================================
    # 10. DETERMINE TOTAL SAMPLE COUNT
    # ========================================================

    all_samples = (
        genotype_df["Sample_Clean"]
        .replace("", np.nan)
        .dropna()
        .drop_duplicates()
        .tolist()
    )

    total_samples = len(all_samples)

    if total_samples == 0:
        raise ValueError(
            "No sample identifiers were found "
            "in the genotype table."
        )

    print(
        f"Total samples detected: {total_samples}"
    )

    # ========================================================
    # 11. BUILD CARRIER SUMMARY
    # ========================================================

    print()
    print(
        "Matching HGVS variants to confirmed "
        "genotype carriers..."
    )
    print()

    carrier_records = []

    for _, hgvs_row in hgvs_df.iterrows():

        hgvs = hgvs_row["HGVS_NORMALISED"]

        ref = normalise_variant_allele(
            hgvs_row["REF"]
        )

        alt = normalise_variant_allele(
            hgvs_row["ALT"]
        )

        transcript_position = to_numeric(
            hgvs_row["Transcript_Position"]
        )

        if pd.isna(transcript_position):
            raise ValueError(
                f"Missing Transcript_Position "
                f"for {hgvs}"
            )

        transcript_position = int(
            transcript_position
        )

        variant_key = build_variant_key(
            transcript_position,
            ref,
            alt,
        )

        # ----------------------------------------------------
        # Only count carriers for confirmed variants
        # ----------------------------------------------------

        if variant_key not in confirmed_variant_keys:

            carriers = []

        else:

            position_matches = (
                confirmed_genotypes[
                    confirmed_genotypes[
                        "cDNA_Position_Numeric"
                    ]
                    == transcript_position
                ]
                .copy()
            )

            position_matches = (
                position_matches[
                    position_matches["REF_Clean"]
                    == ref
                ]
                .copy()
            )

            position_matches = (
                position_matches[
                    position_matches["ALT_Clean"]
                    == alt
                ]
                .copy()
            )

            carriers = (
                position_matches[
                    "Sample_Clean"
                ]
                .replace("", np.nan)
                .dropna()
                .drop_duplicates()
                .tolist()
            )

        carrier_count = len(carriers)

        variant_frequency = (
            carrier_count / total_samples
        )

        samples_string = ";".join(
            carriers
        )

        print(
            f"{hgvs}: "
            f"{carrier_count} carrier(s) -> "
            f"{samples_string if samples_string else 'None'}"
        )

        carrier_records.append({

            # ------------------------------------------------
            # Internal merge key
            # ------------------------------------------------

            "HGVS_NORMALISED": hgvs,

            # ------------------------------------------------
            # Variant identity
            # ------------------------------------------------

            "HGVS_cDNA": hgvs,
            "REF": ref,
            "ALT": alt,

            # ------------------------------------------------
            # Coordinate information
            # ------------------------------------------------

            "Transcript": clean_string(
                hgvs_row["Transcript"]
            ),

            "Transcript_Position": transcript_position,

            "HGVS_cDNA_Position": to_numeric(
                hgvs_row["HGVS_cDNA_Position"]
            ),

            # ------------------------------------------------
            # Genotype-derived information
            # ------------------------------------------------

            "Carrier_Count": carrier_count,

            "Variant_Frequency": variant_frequency,

            "Samples": samples_string,

        })

    carrier_df = pd.DataFrame(
        carrier_records
    )

    # ========================================================
    # 12. VALIDATE CARRIER SUMMARY
    # ========================================================

    required_carrier_columns = [
        "HGVS_NORMALISED",
        "HGVS_cDNA",
        "REF",
        "ALT",
        "Carrier_Count",
        "Variant_Frequency",
        "Samples",
    ]

    missing_carrier = [
        column
        for column in required_carrier_columns
        if column not in carrier_df.columns
    ]

    if missing_carrier:
        raise RuntimeError(
            "Internal carrier summary is missing:\n"
            + "\n".join(
                f"  - {column}"
                for column in missing_carrier
            )
        )

    # ========================================================
    # 13. PREPARE VEP/ENSEMBL ANNOTATION
    # ========================================================

    print()
    print(
        "Loading Ensembl VEP annotation..."
    )

    if annotation_df.empty:

        print(
            "Warning: annotation dataframe is empty. "
            "Final table will contain genotype information "
            "but no functional annotation."
        )

        vep_unique = pd.DataFrame(
            columns=[
                "HGVS_NORMALISED"
            ]
        )

    else:

        annotation_hgvs_candidates = [
            "HGVS_cDNA",
            "#Uploaded_variation",
            "Uploaded_variation",
        ]

        annotation_hgvs_column = None

        for column in annotation_hgvs_candidates:

            if column in annotation_df.columns:
                annotation_hgvs_column = column
                break

        if annotation_hgvs_column is None:
            raise KeyError(
                "Could not identify the HGVS column "
                "in the annotation dataframe.\n\n"
                "Expected one of:\n"
                + "\n".join(
                    f"  - {column}"
                    for column in annotation_hgvs_candidates
                )
            )

        annotation_df["HGVS_NORMALISED"] = (
            annotation_df[
                annotation_hgvs_column
            ]
            .apply(normalise_hgvs)
        )

        vep_unique = (
            annotation_df[
                annotation_df[
                    "HGVS_NORMALISED"
                ] != ""
            ]
            .drop_duplicates(
                subset=[
                    "HGVS_NORMALISED"
                ],
                keep="first",
            )
            .copy()
        )

    # ========================================================
    # 14. CHECK VEP MATCHING
    # ========================================================

    matched_vep = (
        carrier_df[
            ["HGVS_NORMALISED"]
        ]
        .merge(
            vep_unique[
                ["HGVS_NORMALISED"]
            ],
            on="HGVS_NORMALISED",
            how="left",
            indicator=True,
        )
    )

    vep_match_count = (
        matched_vep["_merge"]
        .eq("both")
        .sum()
    )

    print(
        "VEP HGVS matching: "
        f"{vep_match_count} of "
        f"{len(carrier_df)} variants matched."
    )

    # ========================================================
    # 15. MERGE ANNOTATION WITH CARRIER SUMMARY
    # ========================================================

    final_df = carrier_df.merge(
        vep_unique,
        on="HGVS_NORMALISED",
        how="left",
        suffixes=(
            "",
            "_VEP",
        ),
    )

    # ========================================================
    # 16. REMOVE CONFLICTING ANNOTATION FIELDS
    # ========================================================

    # These fields must remain genotype-derived.

    conflicting_columns = [
        "Carrier_Count_VEP",
        "Variant_Carrier_Count",
        "Variant_Frequency_VEP",
        "Samples_VEP",
        "Variant_Calls",
        "Variant_Samples",
        "Genotype_Calls",
        "Genotype_Sample_Count",
    ]

    for column in conflicting_columns:

        if column in final_df.columns:

            final_df.drop(
                columns=[column],
                inplace=True,
            )

    # ========================================================
    # 17. REMOVE INTERNAL ANNOTATION IDENTIFIERS
    # ========================================================

    for column in [
        "#Uploaded_variation",
        "Uploaded_variation",
    ]:

        if column in final_df.columns:

            final_df.drop(
                columns=[column],
                inplace=True,
            )

    # ========================================================
    # 18. PROTECT CORE GENOTYPE INFORMATION
    # ========================================================

    core_genotype_fields = carrier_df[
        [
            "HGVS_cDNA",
            "Carrier_Count",
            "Variant_Frequency",
            "Samples",
        ]
    ].copy()

    for column in [
        "Carrier_Count",
        "Variant_Frequency",
        "Samples",
    ]:

        if column in final_df.columns:

            final_df.drop(
                columns=[column],
                inplace=True,
            )

    final_df = final_df.merge(
        core_genotype_fields,
        on="HGVS_cDNA",
        how="left",
    )

    # ========================================================
    # 19. PROTECT REF / ALT
    # ========================================================

    hgvs_core = hgvs_df[
        [
            "HGVS_NORMALISED",
            "REF",
            "ALT",
        ]
    ].copy()

    hgvs_core["HGVS_cDNA"] = (
        hgvs_core["HGVS_NORMALISED"]
    )

    hgvs_core["REF"] = (
        hgvs_core["REF"]
        .apply(normalise_variant_allele)
    )

    hgvs_core["ALT"] = (
        hgvs_core["ALT"]
        .apply(normalise_variant_allele)
    )

    hgvs_core = hgvs_core[
        [
            "HGVS_cDNA",
            "REF",
            "ALT",
        ]
    ]

    for column in [
        "REF",
        "ALT",
    ]:

        if column in final_df.columns:

            final_df.drop(
                columns=[column],
                inplace=True,
            )

    final_df = final_df.merge(
        hgvs_core,
        on="HGVS_cDNA",
        how="left",
    )

    # ========================================================
    # 20. VARIANT TYPE
    # ========================================================

    if "Variant_Type" not in final_df.columns:

        final_df["Variant_Type"] = np.where(
            (
                final_df["REF"].str.len() == 1
            )
            &
            (
                final_df["ALT"].str.len() == 1
            ),
            "SNV",
            "Other",
        )

    # ========================================================
    # 21. REORDER COLUMNS
    # ========================================================

    preferred_order = [

        # ----------------------------------------------------
        # Variant identity
        # ----------------------------------------------------

        "HGVS_cDNA",
        "REF",
        "ALT",
        "Variant_Type",

        # ----------------------------------------------------
        # Functional annotation
        # ----------------------------------------------------

        "Consequence",
        "Impact",
        "Most_Severe_Consequence",
        "Protein_HGVS",
        "Protein_Position",
        "Amino_Acid_Change",
        "Codon_Change",

        # ----------------------------------------------------
        # Gene annotation
        # ----------------------------------------------------

        "Gene",
        "Gene_ID",
        "SYMBOL",
        "Transcript",
        "Feature",
        "BIOTYPE",

        # ----------------------------------------------------
        # Genomic annotation
        # ----------------------------------------------------

        "Assembly",
        "Chromosome",
        "Genomic_Position",
        "End_Position",
        "Strand",
        "Genomic_Coordinate",
        "HGVS_Genomic",

        # ----------------------------------------------------
        # Database annotation
        # ----------------------------------------------------

        "dbSNP_rsID",
        "Existing_variation",
        "COSMIC_ID",
        "ClinVar_ID",
        "HGMD_ID",

        # ----------------------------------------------------
        # Position annotation
        # ----------------------------------------------------

        "Transcript_Position",
        "cDNA_Position",
        "CDS_Position",
        "HGVS_cDNA_Position",

        # ----------------------------------------------------
        # Genotype-derived information
        # ----------------------------------------------------

        "Carrier_Count",
        "Variant_Frequency",
        "Samples",

        # ----------------------------------------------------
        # Annotation status
        # ----------------------------------------------------

        "Status",

        # ----------------------------------------------------
        # Quality
        # ----------------------------------------------------

        "Mean_Quality",
        "Mean_Alignment_Score",
    ]

    existing_preferred = [
        column
        for column in preferred_order
        if column in final_df.columns
    ]

    remaining_columns = [
        column
        for column in final_df.columns
        if column not in existing_preferred
        and column != "HGVS_NORMALISED"
    ]

    final_df = final_df[
        existing_preferred
        + remaining_columns
    ]

    # ========================================================
    # 22. REMOVE INTERNAL MERGE KEY
    # ========================================================

    if "HGVS_NORMALISED" in final_df.columns:

        final_df.drop(
            columns=["HGVS_NORMALISED"],
            inplace=True,
        )

    # ========================================================
    # 23. FORMAT NUMERIC FIELDS
    # ========================================================

    if "Carrier_Count" in final_df.columns:

        final_df["Carrier_Count"] = (
            pd.to_numeric(
                final_df["Carrier_Count"],
                errors="coerce",
            )
            .fillna(0)
            .astype(int)
        )

    if "Variant_Frequency" in final_df.columns:

        final_df["Variant_Frequency"] = (
            pd.to_numeric(
                final_df["Variant_Frequency"],
                errors="coerce",
            )
        )

    # ========================================================
    # 24. VALIDATE VARIANT COUNT
    # ========================================================

    if len(final_df) != len(hgvs_df):

        raise RuntimeError(
            "\nFINAL VARIANT COUNT ERROR\n"
            f"HGVS variants: {len(hgvs_df)}\n"
            f"Final variants: {len(final_df)}\n"
        )

    # ========================================================
    # 25. VALIDATE HGVS IDENTITY AND ORDER
    # ========================================================

    expected_hgvs = (
        hgvs_df[
            "HGVS_NORMALISED"
        ]
        .tolist()
    )

    final_hgvs = (
        final_df[
            "HGVS_cDNA"
        ]
        .apply(normalise_hgvs)
        .tolist()
    )

    if expected_hgvs != final_hgvs:

        raise RuntimeError(
            "\nHGVS ORDER/IDENTITY ERROR\n\n"
            f"Expected:\n{expected_hgvs}\n\n"
            f"Final:\n{final_hgvs}\n"
        )

    # ========================================================
    # 26. VALIDATE CARRIER COUNTS AND FREQUENCIES
    # ========================================================

    print()
    print("=" * 70)
    print("FINAL CARRIER SUMMARY")
    print("=" * 70)
    print()

    for _, row in final_df.iterrows():

        hgvs = row["HGVS_cDNA"]

        carrier_count = int(
            row["Carrier_Count"]
        )

        frequency = float(
            row["Variant_Frequency"]
        )

        samples = (
            ""
            if pd.isna(row["Samples"])
            else str(row["Samples"])
        )

        if samples in {
            "",
            "-",
            "nan",
        }:

            sample_list = []

        else:

            sample_list = [
                sample.strip()
                for sample in samples.split(";")
                if sample.strip()
            ]

        sample_count = len(
            sample_list
        )

        print(hgvs)

        print(
            f"  REF: {row['REF']}"
        )

        print(
            f"  ALT: {row['ALT']}"
        )

        print(
            f"  Carrier_Count: "
            f"{carrier_count}"
        )

        print(
            f"  Variant_Frequency: "
            f"{frequency:.3f}"
        )

        print(
            f"  Samples: "
            f"{samples if samples else 'None'}"
        )

        print()

        # ----------------------------------------------------
        # Carrier count validation
        # ----------------------------------------------------

        if carrier_count != sample_count:

            raise RuntimeError(
                f"\nCARRIER COUNT ERROR for {hgvs}\n"
                f"Carrier_Count = {carrier_count}\n"
                f"Number of Samples = {sample_count}\n"
                f"Samples = {samples}\n"
            )

        # ----------------------------------------------------
        # Frequency validation
        # ----------------------------------------------------

        expected_frequency = (
            carrier_count / total_samples
        )

        if not np.isclose(
            frequency,
            expected_frequency,
            atol=1e-9,
        ):

            raise RuntimeError(
                f"\nFREQUENCY ERROR for {hgvs}\n"
                f"Carrier_Count = {carrier_count}\n"
                f"Total samples = {total_samples}\n"
                f"Expected frequency = "
                f"{expected_frequency}\n"
                f"Observed frequency = "
                f"{frequency}\n"
            )

    # ========================================================
    # 27. FINAL DISPLAY
    # ========================================================

    print("=" * 70)
    print("FINAL VARIANT TABLE")
    print("=" * 70)
    print()

    display_columns = [
        "HGVS_cDNA",
        "REF",
        "ALT",
        "Consequence",
        "Impact",
        "Carrier_Count",
        "Variant_Frequency",
        "Samples",
    ]

    available_display_columns = [
        column
        for column in display_columns
        if column in final_df.columns
    ]

    print(
        final_df[
            available_display_columns
        ].to_string(
            index=False,
        )
    )

    print()

    return final_df


# ============================================================
# SAVE FINAL TABLE
# ============================================================

def save_final_table(
    final_df: pd.DataFrame,
    output_folder: str,
) -> str:
    """
    Save the final annotated variant table.

    Parameters
    ----------
    final_df : pandas.DataFrame
        Final variant dataframe.

    output_folder : str
        Directory where the table will be saved.

    Returns
    -------
    str
        Path to the saved CSV file.
    """

    output_path = Path(
        output_folder
    )

    output_path.mkdir(
        parents=True,
        exist_ok=True,
    )

    output_file = (
        output_path
        / "Final_Annotated_Variants.csv"
    )

    final_df.to_csv(
        output_file,
        index=False,
    )

    print(
        "=" * 70
    )

    print(
        "Final variant table saved to:"
    )

    print(
        output_file
    )

    print()

    print(
        f"Final number of variants: "
        f"{len(final_df)}"
    )

    print()

    return str(output_file)